# Generated by Django 5.2.4 on 2025-08-06 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0002_remove_group_members_group_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSwipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('disliked_by', models.ManyToManyField(blank=True, related_name='disliked_swipes', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='group_app.group')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_swipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
