# Generated by Django 5.2.4 on 2025-08-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_alter_restaurant_image_url_alter_restaurant_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
