# Generated by Django 5.2.4 on 2025-08-04 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_app', '0001_initial'),
        ('group_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='group_faavorites',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user_faavorites',
        ),
        migrations.AddField(
            model_name='favorite',
            name='group_favorites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='group_app.group'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user_favorites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
