# Generated by Django 5.2.4 on 2025-08-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_app', '0002_remove_favorite_group_faavorites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='review',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
