# Generated by Django 5.2.4 on 2025-08-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_app', '0003_favorite_location_alter_favorite_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
