# Generated by Django 5.2.4 on 2025-08-12 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSwipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('liked', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
